services:
   postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgress
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postresql/data
volumes:
 pgdata:

   
   
        