name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
   Build : 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : run one-line script
        run : echo hello world

      - name : run multipe-line scrit
        run : |
         echo add other action,
         echo test and deploy
   
   
