name : CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


  workflow_dispatch:
  
jobs:
  build:
      runs-on: ubuntu-22.04,
      steps : 
       - uses : actions/checkout@v3

       - name : Run a one-line script
         run : echo Hello, World!
         
       - name : Run a multiple-line script
         run : |
           echo add other action to build,
           echo test and deploy your project.



         
